### PR TITLE
API Simplification RFC

### PR DESCRIPTION
**Pull request by adamlofts**
This is a big PR. I'm opening it to give you a sense of the API change and get comments.

General goal was to make the API hard to mis-use and to improve error handling. There are still a few things incomplete: some tests not ported, SSL may not work, example is not ported, readme needs updating.

Hi-lights of the changes:
* Remove the connection pool
* Add ConnectionSettings class in builder pattern style
* Queue each query locally so there is only ever one outstanding request
* Change transaction api to use a callback pattern
* Export as little API as possible to library users
* Add travis support
* Dartfmt all code
* Do not stream query results to the user. Just return a list of results.
* Add socket_test to verify socket errors are handled correctly
* Add google lints

### CODE REVIEW

**Comment by tejainece** [comment]
This is definitely the way forward.

Can you please fix all merge conflicts? So, we can work on your branch as the main branch.

**Comment by adamlofts** [comment]
I forgot a few more features:

All api has a timeout (default 30 seconds) to prevent apps hanging.
Properly close connections #6

I suspect the merge conflicts are the dart2 changes. I am unable to run
dart2 at the moment so not sure how I can resolve them. I'll have a think
about it. As I say the 1st step would be to get travis running on dart1 &
dart2.

**Comment by tejainece** [comment]
Just resolve the conflicts. Dont have to preserve old changes.

**Comment by adamlofts** [comment]
I merged all the conficts locally... no problem. But you have pulled a change which is not dart1 compatible so I cannot get my tests to pass.

This is the change https://github.com/dart-db/sqljocky5/pull/10/files
for example the use of lower case constants.

Suggest reverting all commits before I branched and then merge this PR.

**Comment by tejainece** [comment]
I dint pull anything. Github says this branch has conflicts. If you resolve them, I will merge. Then we can work on your code.

**Comment by adamlofts** [comment]
I wasn't clear yesterday. The problem is that this commit https://github.com/dart-db/sqljocky5/commit/05f73d9868533bf2e45061b0e7e16b23ba9d0731 means that the master branch no longer supports dart1.

This means if we just fix the conflicts in the PR and merge the lib will not work because it will be half dart1 and half dart2. 

My suggestion is to revert the commits related to dart2 so master supports dart1 again. This will allow this PR to be merge and run correctly.

**Comment by tejainece** [comment]
Override the changes. With your changes. Dont preserve them. I only use Dart2. So I will make those Dart2 fixes. It will be good if everyone works on the latest code. Otherwise more commits will pile up.

**Comment by adamlofts** [comment]
Alright I've updated the PR to resolve conflicts. 

As I say - This branch no longer passes any tests and travis will fail because it is half dart1 and half dart2.

**Comment by tejainece** [comment]
Its ok. We will fix it :).

**Comment by adamlofts** [comment]
Just saw your message on gitter, maybe this justifies a new package.

**Comment by kaetemi** [comment]
Can you clarify what you mean by "Do not stream query results to the user. Just return a list of results."?

Currently I'm using the following way to read the results asynchronously:

```
      sqljocky.Results results = await sql.prepareExecute("SELECT * FROM `devices` WHERE `device_id` = ?", [ deviceId ]);
      await for (sqljocky.Row row in results) {
        // ...
      }
```

**Comment by tejainece** [comment]
In the new API, that would return a `List`. You would not need `await for`.

**Comment by kaetemi** [comment]
So it's "less efficient" with huge data.

**Comment by tejainece** [comment]
Maybe. First priority is a stable API.

Once the code is stable in Dart 2.0, we will probably have a streamed call as well.

**Comment by tejainece** [comment]
Will add back streamed response.

**Comment by adamlofts** [comment]
The problem with streams is that they provide unpredictable memory usage. the point of streaming is presumably so you can process results without keeping the whole result set in memory. But if the app isn't processing rows fast enough all of the results will end up in memory anyway as they are put into the stream. so they don't actually provide the utility that they suggest.

Note - for small numbers of rows non-streaming could well be faster because there are fewer async callbacks.

**Comment by tejainece** [comment]
Added a separate API called `queryStreamed` to get `StreamedResults`. The method is here: https://github.com/dart-db/sqljocky5/blob/master/lib/connection/connection.dart#L104

An example is here: https://github.com/dart-db/sqljocky5/blob/master/example/example_streamed.dart#L51

**Comment by adamlofts** [comment]
@kaetemi @tejainece Interesting commit but I think as implemented if you start streaming results and then stream a new query before you finished the driver will crash. You could argue this is a user error and that there is a trade off between usability and performance.

**Comment by tejainece** [comment]
@adamlofts I think if implemented correctly it wont crash but wait for previous handler to complete. So far, it is just a demonstration of how it shall he done.

**Pull request merged**
